# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml uv.lock ./
COPY biomart-mcp.py ./

# Install dependencies
RUN pip install --no-cache-dir mcp[cli]>=1.3.0 pybiomart>=0.2.0

# Expose any needed port (not strictly required for stdio)

# Default command to run MCP server
CMD ["python", "biomart-mcp.py"]
